### ISSUE TITLE
Off Topic: Vector{X} or Array{X,1}? 

### ISSUE THREAD

**Issue by ghost** [rahulkp220/HackerNews.jl#3]
Hello again! 😸 

I've been working on a systematic review of some Julia libraries, and I've started wondering if it's better to use `Array{X,1}` or `Vector{X}`. 
Here's an example use of Array{X,1} in the test code for this repo:  

https://github.com/rahulkp220/HackerNews.jl/blob/dd613e51c3168ba4e3ad808d11ad76032a5d4b74/test/runtests.jl#L30

I like `Array{X,1}`
- I'm used to thinking of Vectors and Arrays as distinct types from C++ experience and game coding experience (Points/Vectors are sometimes implemented as structs in some code I've seen.), I imagine new readers of julia code could have the same confusion. 
- I like how specific it is...  

I'm pretty sure `Vector{X}` is the right thing to do... 
- Less verbose / Less noise. 
- Vector is an assignment to Array{X,1}, so it is equivalent...  (Example for AbstractVector{X} here: https://github.com/JuliaLang/julia/blob/b4af81d347c306de7469213ac5dab047c688b651/base/array.jl#L23) 

What are your feelings about this? 

Oh and on topic, would it be better to do a test to see if the result in that test is `<:AbstractArray{HNUser,1}` rather than `==`? That way you could have flexibility on the returned iterated type?

**Comment by rahulkp220** [comment]
Well, for me both are more or less the same. 
```
julia> Vector
Array{Int64,1}

# or even
julia> Matrix
Array{T,2} where T
```
I understand the viewpoint but I don't find it exciting for this library in particular. 🙂

**Comment by ghost** [comment]
oh it's not exciting at all. 
just curious LUL
